operator creategenericmpoint alias CREATEGENERICMPOINT pattern op ( _ , _ )
operator creategenericpoint alias CREATEGENERICPOINT pattern op ( _ , _ )
operator mapping alias MAPPING pattern op ( _ , _ )
operator map2fs alias MAP2FS pattern op ( _ )
operator map2network alias MAP2NETWORK pattern op ( _ , _ )
operator distance_point alias DISTANCE_POINT pattern op (_, _)
operator gmo_present alias GMO_PRESENT pattern op ( _, _ )
operator gmo_between alias GMO_BETWEEN pattern op (_ , _ , _)
operator gmo_duration alias GMO_DURATION pattern op (_ , _ )
operator gmo_subsequence alias GMO_SUBSEQUENCE pattern op (_ , _ )

